package visao;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.dao.autoridadedao;

/**
 *
 * @author victor tesoura jr
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        txtcodigo.setDocument(new numero());
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelfundo = new javax.swing.JPanel();
        jLabellogo = new javax.swing.JLabel();
        jLabeltitulo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtsenha = new javax.swing.JPasswordField();
        jLabelcodigo = new javax.swing.JLabel();
        jLabelsenha = new javax.swing.JLabel();
        btnentrar = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        jLabeltexto = new javax.swing.JLabel();
        jLabelfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MPDC");
        setName("login"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelfundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1031, -1));

        jLabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logo.png"))); // NOI18N
        getContentPane().add(jLabellogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 280, 280));

        jLabeltitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabeltitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltitulo.setText("Número Único Portuário | NUP");
        getContentPane().add(jLabeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, -1));

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtcodigo.setBorder(null);
        getContentPane().add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 460, -1));

        txtsenha.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtsenha.setBorder(null);
        txtsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsenhaKeyPressed(evt);
            }
        });
        getContentPane().add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 460, -1));

        jLabelcodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelcodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcodigo.setText("Codigo");
        getContentPane().add(jLabelcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        jLabelsenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelsenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsenha.setText("Senha");
        getContentPane().add(jLabelsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        btnentrar.setBackground(new java.awt.Color(0, 255, 204));
        btnentrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnentrar.setForeground(new java.awt.Color(255, 255, 255));
        btnentrar.setText("Iniciar Sessao");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        btnentrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnentrarKeyPressed(evt);
            }
        });
        getContentPane().add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 200, -1));

        btnsair.setBackground(new java.awt.Color(204, 204, 204));
        btnsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/Fechar.png"))); // NOI18N
        btnsair.setBorder(null);
        btnsair.setBorderPainted(false);
        btnsair.setOpaque(false);
        btnsair.setPreferredSize(new java.awt.Dimension(50, 50));
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });
        getContentPane().add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabeltexto.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabeltexto.setForeground(new java.awt.Color(255, 255, 255));
        jLabeltexto.setText("O presente sistema apenas pode ser acedido por utilizadores autorizados, estando as sessões sujeitas a monitorização.");
        jLabeltexto.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabeltexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 1320, 40));

        jLabelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/14.jpg"))); // NOI18N
        jLabelfundo.setText("jLabel1");
        getContentPane().add(jLabelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        dispose();
    }//GEN-LAST:event_btnsairActionPerformed

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        autoridadedao dao = new autoridadedao();
        int c = Integer.parseInt(txtcodigo.getText());

        if (txtcodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor digite o codigo.", "Campo em branco", JOptionPane.WARNING_MESSAGE);

        } else if (txtsenha.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor digite a senha.", "Campo em branco", JOptionPane.WARNING_MESSAGE);

        } else if (txtcodigo.getText().equals("0") && txtsenha.getText().equals("mpdc")) {
            admin tela = new admin();
            tela.setVisible(true);
            dispose();
        } else {
            try {
                if (dao.verificar(c, txtsenha.getText())) {

                    new func().setVisible(true);
                    this.dispose();

                } else {
                    txtcodigo.setText("");
                    txtsenha.setText("");
                    JOptionPane.showMessageDialog(null, "Codigo e/ou Senha incorrecto(a).", "Dados incorrectos", JOptionPane.ERROR_MESSAGE);
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnentrarActionPerformed

    private void txtsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsenhaKeyPressed

    }//GEN-LAST:event_txtsenhaKeyPressed

    private void btnentrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnentrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dispose();
        }
    }//GEN-LAST:event_btnentrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows 10".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnsair;
    private javax.swing.JLabel jLabelcodigo;
    private javax.swing.JLabel jLabelfundo;
    private javax.swing.JLabel jLabellogo;
    private javax.swing.JLabel jLabelsenha;
    private javax.swing.JLabel jLabeltexto;
    private javax.swing.JLabel jLabeltitulo;
    private javax.swing.JPanel jPanelfundo;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
